// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  angular.module("jobFoundryApp").controller("DecisionTreeCtrl", function($scope) {
    var $s, curNode;

    $s = $scope;
    $s.tree = {
      a: {
        question: "What would you like to build?",
        options: [
          {
            name: "Web Application",
            child: "b"
          }, {
            name: "Mobile Application",
            child: "c"
          }, {
            name: "Social Media Presence",
            child: ""
          }
        ],
        parent: ""
      },
      b: {
        question: "What kind of content will you be hosting?",
        options: [
          {
            name: "Static Content",
            child: ""
          }, {
            name: "Dynamic Content",
            child: ""
          }
        ],
        parent: "a"
      },
      c: {
        question: "Which platform are you targetting?",
        options: [
          {
            name: "iOS",
            child: ""
          }, {
            name: "Android",
            child: ""
          }, {
            name: "Mobile Web",
            child: ""
          }
        ],
        parent: "a"
      }
    };
    curNode = $s.tree.a;
    $s.curQuestion = curNode.question;
    $s.options = curNode.options;
    return $s.step = function(option) {
      curNode = $s.tree[option.child];
      $s.curQuestion = curNode.question;
      return $s.options = curNode.options;
    };
  });

}).call(this);
