// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  angular.module("resourceFoundryApp").controller("LandingCtrl", function($scope) {
    return $scope.options = ["Web Application", "Mobile Application", "Social Media Presence"];
  });

}).call(this);
