// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module("jobFoundryApp").controller("LandingCtrl", function($scope) {
    $scope.subscribe = false;
    return $scope.options = ["Web Application", "Mobile Application", "Social Media Presence"];
  });

}).call(this);
