// Generated by CoffeeScript 1.6.3
angular.module('resourceFoundryApp').controller('ListCtrl', function($scope, $routeParams, map, Resources) {
  $scope.valueFor = map;
  $scope.resources = Resources.get();
  return $scope.path = $routeParams.path;
});
