// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('resourceFoundryApp').controller('ListCtrl', function($scope, $routeParams, map, levels, Resources) {
    $scope.valueFor = map;
    $scope.levels = levels;
    $scope.resources = Resources.get();
    return $scope.path = $routeParams.path;
  });

}).call(this);
