// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('resourceFoundryApp').controller('ListCtrl', function($scope, $routeParams, map, levels, Resources) {
    $scope.valueFor = map;
    $scope.levels = levels;
    $scope.resources = Resources.get();
    $scope.path = $routeParams.path;
    return $scope.deleteResource = function(resource) {
      if (confirm("Are you sure you want to delete this resource?")) {
        return Resources["delete"](resource);
      }
    };
  });

}).call(this);
