// Generated by CoffeeScript 1.6.3
'use strict';
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

angular.module('resourceFoundryApp').controller('MainCtrl', function($scope, Resources, mediaTypes, topics, levels, costs, paths, map) {
  $scope.mediaTypes = mediaTypes;
  $scope.topics = topics;
  $scope.levels = levels;
  $scope.costs = costs;
  $scope.paths = paths;
  $scope.valueFor = map;
  Resources.get().then(function(resources) {
    $scope.resources = resources;
    return $scope.authors = _(resources, "authors").pluck().flatten().uniq(JSON.stringify);
  });
  $scope.authorCount = 1;
  $scope.input = {};
  $scope.input.authors = [
    [
      {
        key: "name",
        value: ""
      }
    ]
  ];
  $scope.addAuthorAttr = function(author, attr) {
    if (attr && __indexOf.call(_.pluck(author, "key"), attr) < 0) {
      return author.push({
        key: attr,
        value: ""
      });
    }
  };
  $scope.$watch('authorCount', function(newVal) {
    var diff, _results, _results1;
    if (newVal <= 0) {
      return;
    }
    diff = newVal - $scope.input.authors.length;
    if (diff > 0) {
      _results = [];
      while (diff-- > 0) {
        _results.push($scope.input.authors.push([
          {
            key: "name",
            value: ""
          }
        ]));
      }
      return _results;
    } else if (diff < 0) {
      _results1 = [];
      while (diff++ < 0) {
        _results1.push($scope.input.authors.pop());
      }
      return _results1;
    }
  });
  return $scope.addResource = function() {
    var input;
    input = angular.copy($scope.input);
    if (!(input.level && input.path && input.cost)) {
      alert("you must have a level, path and cost");
      return;
    }
    input.authors = input.authors.map(function(attrs) {
      var author;
      author = {};
      _.each(attrs, function(attr) {
        return author[attr.key] = attr.value;
      });
      return author;
    });
    Resources.add(_.defaults(input, {
      topic: [],
      mediaType: [],
      description: "",
      authors: [
        {
          name: ""
        }
      ],
      cost: "free"
    }));
    return $scope.input = {
      authors: []
    };
  };
});
