// Generated by CoffeeScript 1.6.3
'use strict';
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

angular.module('resourceFoundryApp').filter('capitalise', function() {
  return function(input) {
    return input.charAt(0).toUpperCase() + input.slice(1);
  };
});

angular.module('resourceFoundryApp').controller('MainCtrl', function($scope, $http) {
  $http({
    method: 'GET',
    url: '/data.json'
  }).success(function(data, status, config) {
    $scope.authors = _.uniq(_.flatten(_.pluck(data, "authors")), JSON.stringify);
    $scope.mediaTypes = _.uniq(_.flatten(_.pluck(data, "mediaType")));
    $scope.topics = _.uniq(_.flatten(_.pluck(data, "topic")));
    $scope.authorSelectOptions.data = $scope.authors;
    $scope.topicOptions = {
      tags: $scope.topics
    };
    return window.$scope = $scope;
  }).error(function() {
    return console.log('error :(');
  });
  $scope.$watch('input.levelsTest', function(newVal, oldVal, scope) {
    return console.log(newVal, oldVal, scope);
  });
  $scope.paths = [
    {
      key: "webdevelopment",
      name: "Web Development"
    }, {
      key: "marketing",
      name: "Marketing"
    }
  ];
  $scope.levels = ["beginner", "intermediate", "expert", "all"];
  $scope.topics = ["html", "css", "javascript", "frontend"];
  $scope.mediaTypes = ["article", "reference", "tutorial", "tool", "talk", "video"];
  $scope.authorSelectOptions = {
    multiple: false,
    createSearchChoice: function(term, data) {
      console.log(term, data);
      if (__indexOf.call(data, term) < 0) {
        return {
          id: term,
          text: term
        };
      } else {
        return null;
      }
    }
  };
  $scope.resources = [
    {
      path: "webdevelopment",
      title: "Google",
      link: "http://www.apple.com",
      level: "all",
      topics: ["html", "css", "javascript"],
      mediaTypes: ["reference", "tutorial", "tool"]
    }
  ];
  return $scope.addResource = function() {
    $scope.resources.push({
      path: $scope.input.path,
      title: $scope.input.title,
      link: $scope.input.url,
      level: $scope.input.level,
      topics: _.pluck($scope.input.topics, "id"),
      mediaTypes: _.pluck($scope.input.types, "id"),
      description: $scope.input.description
    });
    return $scope.input = {};
  };
});
