// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  angular.module('resourceFoundryApp').controller('MainCtrl', function($scope, Resources, mediaTypes, topics, levels, costs, paths, map) {
    $scope.mediaTypes = mediaTypes;
    $scope.topics = topics;
    $scope.levels = levels;
    $scope.costs = costs;
    $scope.paths = paths;
    $scope.valueFor = map;
    $scope.resources = Resources.get();
    $scope.authorCount = 1;
    $scope.input = {
      authors: [
        [
          {
            key: "name",
            value: ""
          }
        ]
      ],
      cost: "free"
    };
    $scope.testData = function() {
      return $scope.input = {
        path: "webdevelopment",
        level: "all",
        title: "Google",
        link: "http://google.com",
        topic: ["html"],
        mediaType: ["tool"],
        authors: [
          [
            {
              key: "name",
              value: "Sergy Brin"
            }, {
              key: "organisation",
              value: "Google"
            }
          ], [
            {
              key: "name",
              value: "Larry Page"
            }, {
              key: "organisation",
              value: "Google"
            }
          ]
        ],
        cost: "free",
        description: "BEST SITE EVER USE IT FOR EVERYTHING"
      };
    };
    $scope.addAuthorAttr = function(author, attr) {
      if (attr && __indexOf.call(_.pluck(author, "key"), attr) < 0) {
        return author.push({
          key: attr,
          value: ""
        });
      }
    };
    $scope.removeAuthorAttr = function(author, attr) {
      var i, val, _i, _len;
      for (i = _i = 0, _len = author.length; _i < _len; i = ++_i) {
        val = author[i];
        if (val.key === attr) {
          author.splice(i, 1);
          return;
        }
      }
    };
    $scope.$watch('authorCount', function(newVal) {
      var diff, _results;
      if (newVal <= 0) {
        return;
      }
      diff = newVal - $scope.input.authors.length;
      if (diff > 0) {
        _results = [];
        while (diff-- > 0) {
          _results.push($scope.input.authors.push([
            {
              key: "name",
              value: ""
            }
          ]));
        }
        return _results;
      } else if (diff < 0) {
        if (diff === -1) {
          return $scope.input.authors.pop();
        } else {
          return $scope.input.authors.splice($scope.input.authors.length - 1 + diff, diff * -1);
        }
      }
    });
    return $scope.addResource = function() {
      var input;
      input = angular.copy($scope.input);
      if (!(input.level && input.path && input.cost)) {
        alert("you must have a level, path and cost");
        return;
      }
      input.authors = input.authors.map(function(attrs) {
        var author;
        author = {};
        _.each(attrs, function(attr) {
          return author[attr.key] = attr.value;
        });
        return author;
      });
      return Resources.add(_.defaults(input, {
        topic: [],
        mediaType: [],
        description: "",
        authors: [
          {
            name: ""
          }
        ],
        cost: "free"
      })).then(function(res) {
        if (res.success) {
          return $scope.input = {
            authors: []
          };
        } else {
          console.log(res);
          return alert('there was an error with your request, see console for details');
        }
      });
    };
  });

}).call(this);
