// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  Array.prototype.remove = function(e) {
    var i;
    if ((i = this.indexOf(e)) !== -1) {
      return this.splice(i, 1);
    }
  };

  angular.module('resourceFoundryApp', ['resourceFoundryDirectives', 'resourceFoundryServices', 'resourceFoundryData', 'ui.bootstrap', 'ngResource']).config(function($routeProvider, $locationProvider) {
    $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).when('/edit/:id', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).when('/list/:path', {
      templateUrl: 'views/list.html',
      controller: 'ListCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
