// Generated by CoffeeScript 1.6.3
"use strict";
angular.module('resourceFoundryApp', ['ui.select2', 'resourceFoundryDirectives']).config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).otherwise({
    redirectTo: '/'
  });
});
