// Generated by CoffeeScript 1.6.3
angular.module('resourceFoundryDirectives', []);

angular.module('resourceFoundryDirectives').directive('tag', function() {
  return {
    restrict: 'A',
    replace: true,
    scope: {
      remove: "&",
      tag: "="
    },
    template: "<span class=\"tag label label-info\">\n  <span class=\"name\">{{tag}}</span>\n  <a class=\"delete\" href=\"\" ng-show=\"deletable\" ng-click=\"remove({tagName: tag})\">x</a>\n  <input type=\"hidden\" value=\"{{tag}}\">\n</span>",
    link: function(scope, elem, attrs) {
      if (attrs.deletable != null) {
        return scope.deletable = true;
      }
    }
  };
});

angular.module('resourceFoundryDirectives').directive('keyup', function() {
  return {
    restrict: 'A',
    link: function(scope, elem, attrs) {
      return elem.bind('keyup', function(e) {
        return scope.$apply(attrs.keyup);
      });
    }
  };
});

angular.module('resourceFoundryDirectives').directive('tagInput', function() {
  return {
    restrict: 'E',
    scope: {
      tagSuggest: '=tags'
    },
    template: "<form class=\"tag-input\" ng-submit=\"addTag()\">\n  <input keyup=\"suggest()\" type=\"text\" class=\"tag\" ng-model=\"tagInput\">\n  <div class=\"suggest\">\n    <div class=\"suggestion\" ng-repeat=\"tag in suggestions\">{{tag}}</div>\n  </div>\n  <button class=\"btn btn-primary\" type=\"submit\">Add Tag</button>\n  <div tag=\"tag\" ng-repeat=\"tag in tagList\" remove=\"removeTag(tagName)\" deletable></div>\n</form>",
    link: function(scope, elem, attrs) {
      scope.tagList = [];
      scope.suggestions = [];
      scope.addTag = function() {
        scope.tagList.push(scope.tagInput);
        return scope.tagInput = "";
      };
      scope.removeTag = function(name) {
        return scope.tagList = _.without(scope.tags, name);
      };
      return scope.suggest = function() {
        if (scope.tagInput.length > 0) {
          return scope.suggestions = _.take(_.filter(scope.tagSuggest, function(tag) {
            return _contains(tag, scope.tagInput);
          }), 5);
        } else {
          return scope.suggestions = [];
        }
      };
    }
  };
});
